services:
  application:
    build:
        context: .
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - database
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor

  database:
    image: mysql:latest
    container_name: mysql_dev
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
