apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials
      containers:
      - name: php-apache
        image: harbor.tewe.com.br/platform/raspapremio.biz@sha256:6cba692a9e4311da40f584b4becd935b32184856f53811ae3930c720931c0ffb
        ports:
          - containerPort: 80
        env:
          - name: MAINTENANCE
            value: "false"
          - name: MAINTENANCE_ALLOWED_IPS
            value: "191.177.163.136"
          - name: DATABASE_HOST
            value: "mysql"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: "meu_banco"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
