apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials
      containers:
      - name: php-apache
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:0447c22cd12b57bbdcc36f95255eb639891a2b9e65b4edfb70c43727afb09621
        ports:
          - containerPort: 80
        env:
          - name: MAINTENANCE
            value: "true"
          - name: MAINTENANCE_ALLOWED_IPS
            value: "191.177.163.136"
          - name: DATABASE_HOST
            value: "mysql"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: "meu_banco"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
