apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials
      containers:
      - name: php-apache
        image: harbor.tewe.com.br/platform/raspapremio.biz@sha256:eac4a83c2df2fd6b7aaf1ca79f6cab332949b515e0e52ffb529ebdd31bc77870
        ports:
          - containerPort: 80
        env:
          - name: MAINTENANCE
            value: "false"
          - name: MAINTENANCE_ALLOWED_IPS
            value: "191.177.163.136"
          - name: DATABASE_HOST
            value: "mysql"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: "meu_banco"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
