apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      securityContext:
        fsGroup: 82

      imagePullSecrets:
      - name: harbor-credentials

      volumes:
      - name: shared-code
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-config

      initContainers:
      - name: copy-app-code
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:8985eb8ac68af386a9ddc222c40bd1bc4598f516cb29c5e38626c0f27e8a5ae5
        command: ['/bin/sh', '-c', 'cp -r /var/www /app-code']
        volumeMounts:
        - name: shared-code
          mountPath: /app-code
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-code
          mountPath: /var/www/
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true

      - name: php-fpm
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:8985eb8ac68af386a9ddc222c40bd1bc4598f516cb29c5e38626c0f27e8a5ae5
        env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: "meu_banco"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
        volumeMounts:
        - name: shared-code
          mountPath: /var/www
