apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      securityContext:
        runAsUser: 82
        runAsGroup: 82
        fsGroup: 82

      imagePullSecrets:
      - name: harbor-credentials

      volumes:
      - name: shared-code
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-cache
        emptyDir: {}

      initContainers:
      - name: copy-app-code
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:b3f817810a3fe9012db799948749a6d50f1a73d35221164a1053926cc9ec5418
        command: ['/bin/sh', '-c', 'cp -r /var/www/. /app-code/']
        volumeMounts:
        - name: shared-code
          mountPath: /app-code
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-code
          mountPath: /var/www/
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx

      - name: php-fpm
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:b3f817810a3fe9012db799948749a6d50f1a73d35221164a1053926cc9ec5418
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Garante que o PHP-FPM saiba que seu diretório de trabalho é /var/www
            sed -i 's#;chdir = /var/www#chdir = /var/www#g' /usr/local/etc/php-fpm.d/www.conf;
            # Inicia o processo principal
            php-fpm
        env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: "meu_banco"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
        volumeMounts:
        - name: shared-code
          mountPath: /var/www
