apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials

      volumes:
      - name: shared-code
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      # Este volume de logs não é mais necessário, pois seu Nginx agora loga para stdout/stderr
      # - name: nginx-logs
      #   emptyDir: {}

      containers:
      - name: nginx
        image: nginx:stable-alpine
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-code
          mountPath: /var/www/html
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /run
        # Este volumeMount também não é mais necessário
        # - name: nginx-logs
        #   mountPath: /home/thelord.space/logs

      - name: php-fpm
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:af3e4424a2c47b2d44ae2e8c767d48772ff798ef55945d1b8981ae62e5bac92a
        env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: "meu_banco"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /var/www. /app-code-volume/"]
        volumeMounts:
        - name: shared-code
          mountPath: /app-code-volume
