apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials

      volumes:
      - name: app-code-volume
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}

      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        startupProbe:
          exec:
            command:
            - test
            - -f
            - /var/www/html/index.php
          failureThreshold: 30
          periodSeconds: 5
        volumeMounts:
        - name: app-code-volume
          mountPath: /var/www/html
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /run

      - name: php-fpm
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:dcb84cefb483497255f0b658c00a81c02bc2aadf7ac48b697c4ca234d0aa2df2
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "set -ex; cp -r /var/www/. /var/www/html/"]
        volumeMounts:
        - name: app-code-volume
          mountPath: /var/www/html
        env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: "meu_banco"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
