apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        # --- ALTERAÇÃO 1: Mude o root para o caminho do volume ---
        root /app-code;
        index index.php;

        access_log /dev/stdout;
        error_log /dev/stderr;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass   127.0.0.1:9000;
            # --- ALTERAÇÃO 2: Aponte o SCRIPT_FILENAME para o novo root ---
            fastcgi_param  SCRIPT_FILENAME /app-code$fastcgi_script_name;
        }
    }
