apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        # Usaremos /var/www/html como o diretório raiz.
        root /var/www/html;
        index index.php;

        access_log /dev/stdout;
        error_log /dev/stderr;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass   127.0.0.1:9000;
            # Garante que o Nginx passe o caminho correto para o PHP-FPM
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
