apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials

      volumes:
      - name: shared-code
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}

      initContainers:
      - name: copy-app-code
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:6ccd779d472634debd7bbd7f6e97b7ca03953d84498a563fe3d4581cb7b32e10
        command: ['/bin/sh', '-c', 'cp -r /var/www/. /app-code/']
        volumeMounts:
        - name: shared-code
          mountPath: /app-code
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-code
          mountPath: /var/www/
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /run

      - name: php-fpm
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:6ccd779d472634debd7bbd7f6e97b7ca03953d84498a563fe3d4581cb7b32e10
        env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: "meu_banco"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
        volumeMounts:
        - name: shared-code
          mountPath: /var/www
