apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials
      containers:
      - name: php-apache
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:cd790e09efcdf4aa0035459e1d0ab8e5215c14aa23d96a867eee3c36e23dc0eb
        ports:
          - containerPort: 80
        env:
          - name: MAINTENANCE
            value: "true"
          - name: DATABASE_HOST
            value: "mysql"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: "meu_banco"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
