apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials
      containers:
      - name: php-apache
        image: harbor.tewe.com.br/platforms/raspapremio@sha256:24889f3ed6bea90ffa88c65a6c42ce577beed813766ab92ddbffa44d4c39a4f3
        ports:
          - containerPort: 80
        env:
          - name: DATABASE_HOST
            value: "mysql"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: "meu_banco"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
