apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      imagePullSecrets:
      - name: harbor-credentials
      containers:
      - name: php-apache
        image: harbor.tewe.com.br/platform/raspapremio.biz@sha256:509139fa84b78528a1e8019387004c9f53f93c56a653dec89f2dba1b68e5e68b
        ports:
          - containerPort: 80
        env:
          - name: MAINTENANCE
            value: "true"
          - name: MAINTENANCE_ALLOWED_IPS
            value: "191.177.163.136"
          - name: DATABASE_HOST
            value: "mysql"
          - name: BASE_URL
            value: "https://raspapremio.biz"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: "meu_banco"
          - name: DATABASE_USER
            value: "root"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
