apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IudGV3ZS5jb20uYnIiOnsidXNlcm5hbWUiOiJnaXRvcHMiLCJwYXNzd29yZCI6Ik1DYXNkUVdFUiFAIzExIiwiYXV0aCI6IloybDBiM0J6T2sxRFlYTmtVVmRGVWlGQUl6RXhRR0ZoIn19fQ==
