name: Build and Push Docker Image to Harbor

on:
  push:
    branches: [ "main" ]

env:
  APP_NAME: 'raspapremio'
  ENVIRONMENT_NAME: 'raspapremio'

jobs:
  build-and-push:
    environment: ${{ env.ENVIRONMENT_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/platforms/${{ env.APP_NAME }}:latest
            ${{ secrets.HARBOR_REGISTRY }}/platforms/${{ env.APP_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
